// Generate the app's copy of the board's constants from the design canvas.
//
// `board.mjs` is the single definition of the board — the palette, the piece shapes, the
// token metrics, the glyphs, the lattice taper. The React board needs the same numbers, and
// copying them by hand is how a spec and an implementation drift apart quietly. This writes
// them instead, so drift shows up as a diff.
//
//   node web/design/export-tokens.mjs
//
// Re-run it after any change to board.mjs or glyphs.mjs; it is idempotent.
import { writeFileSync } from 'node:fs';
import { C, SEAT, SEAT_HI, SEAT_LO, TOKEN, CX, CY, R, TAPER_IN, TAPER_OUT,
         SET, CITY, RES_ORDER, PORT_R, portFill, glyphMini } from './board.mjs';
import { GLYPHS } from './glyphs.mjs';

// board.mjs keeps these module-private because nothing else needed them; pull them out of
// a rendered piece rather than re-deriving them by hand.
import { piece } from './board.mjs';
const shapeOf = (kind, i) => {
  const g = piece(kind, 'red', 0, 0);
  const polys = [...g.matchAll(/<polygon points="([^"]+)"/g)].map(m => m[1]);
  return polys[i].split(' ').map(p => p.split(',').map(Number));
};

const RES = ['wood', 'brick', 'sheep', 'wheat', 'ore'];
const mini = {};
for (const res of RES) {
  const g = glyphMini(res, 0, 0, 18, 14);
  mini[res] = {
    k: +/scale\(([\d.]+)\)/.exec(g)[1],
    dx: +/translate\((-?[\d.]+),(-?[\d.]+)\)">/.exec(g)[1],
    dy: +/translate\((-?[\d.]+),(-?[\d.]+)\)">/.exec(g)[2],
    markup: g.slice(g.indexOf('>') + 1, g.lastIndexOf('</g>')),
  };
}

const j = v => JSON.stringify(v);
const out = `// GENERATED by web/design/export-tokens.mjs — do not edit by hand.
// The board's constants, from the design canvas's board.mjs. See docs/UI-REWRITE.md.
/* eslint-disable */

export const C = ${j(C)} as const;
export const SEAT = ${j(['red','blue','orange','grey'])} as const;
export const SEAT_FILL = ${j([SEAT.red, SEAT.blue, SEAT.orange, SEAT.grey])};
export const SEAT_HI = ${j([SEAT_HI.red, SEAT_HI.blue, SEAT_HI.orange, SEAT_HI.grey])};
export const SEAT_LO = ${j([SEAT_LO.red, SEAT_LO.blue, SEAT_LO.orange, SEAT_LO.grey])};

/** Resource index (the engine's) to name. -1 is the desert, or a generic port. */
export const RES = ${j(RES)} as const;
export const RES_FILL = ${j(RES.map(r => C[r]))};
export const DESERT_FILL = ${j(C.desert)};

export const CX = ${CX}, CY = ${CY}, R = ${R};
export const TAPER_IN = ${TAPER_IN}, TAPER_OUT = ${TAPER_OUT};

/** Larger than the old r 13.2: five-pip rows had 1.16 units of clearance to the sloping
 *  edge, and now have 3.36. */
export const TOKEN = ${j(TOKEN)};

/** Piece outlines, already centred on the corner they stand at. */
export const SET = ${j(SET)};
export const SET_ROOF = ${j(shapeOf('set', 2))};
export const CITY = ${j(CITY)};
export const CITY_TOWER = ${j(shapeOf('city', 2))};
export const CITY_DOOR = ${j(shapeOf('city', 3))};

/** Ports: filled like a tile, no stroke, the fill lightened a fifth toward the ground so
 *  pine ink clears 4.5:1 on wood and brick too. */
export const PORT_R = ${PORT_R};
export const PORT_FILL = ${j(RES_ORDER.map((_, i) => portFill(i)))};
export const PORT_GENERIC_FILL = ${j(portFill(-1))};

/** One motif of each watermark, fitted to an 18x14 box: one wheat stalk where the tile
 *  draws three. Placed as translate(cx,cy) scale(k) translate(dx,dy). */
export const GLYPH_MINI: Record<string, { k: number; dx: number; dy: number; markup: string }> = ${j(mini)};

/** The full watermarks, each authored against the tile centre in \`origin\`. */
export const GLYPH: Record<string, { origin: [number, number]; markup: string }> = ${j(
  Object.fromEntries(Object.entries(GLYPHS).map(([k, v]) => [k, { origin: v.origin, markup: v.markup }]))
)};
`;

const path = new URL('../src/board/palette.ts', import.meta.url).pathname;
writeFileSync(path, out);
console.log('wrote', path, `(${(out.length / 1024).toFixed(1)}K)`);
