"""Dump the constants the Rust engine needs to generate BASE boards without catanatron:
  catan_engine/src/base_topology.rs   node ids per tile/port, neighbour order, resource multisets, spiral order
  catan_engine/src/base_layout.json   rust_bridge.layout spec + tile/port static feature indices
  web/src/data/topology.json          the same topology plus pixel coordinates for the board renderer
Run after any change to catan_env.LAYOUT or the pinned catanatron: `uv run python tools/dump_engine_consts.py`.
"""

import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from catanatron.game import Game
from catanatron.models.board import STATIC_GRAPH
from catanatron.models.enums import RESOURCES, NodeRef
from catanatron.models.map import (
    BASE_MAP_TEMPLATE, BASE_NUMBERS_IN_SPIRAL_ORDER, PORT_DIRECTION_TO_NODEREFS, LandTile, Port, spiral_land_coordinates,
)
from catanatron.models.player import Color, RandomPlayer

import rust_bridge as rb
from catan_env import LAYOUT

ROOT = Path(__file__).resolve().parents[1]
ORDER = [NodeRef.NORTH, NodeRef.NORTHEAST, NodeRef.SOUTHEAST, NodeRef.SOUTH, NodeRef.SOUTHWEST, NodeRef.NORTHWEST]
RES_IDX = {r: i for i, r in enumerate(RESOURCES)}

game = Game([RandomPlayer(c) for c in (Color.RED, Color.BLUE, Color.ORANGE, Color.WHITE)], seed=1)
cmap = game.state.board.map
ctx = rb.ctx_for(game)

tiles = []
for tid in range(len(cmap.tiles_by_id)):
    t = cmap.tiles_by_id[tid]
    tiles.append({"id": tid, "coord": list(ctx.coord_of[tid]), "nodes": [t.nodes[k] for k in ORDER]})
ports = []
for coord, t in cmap.tiles.items():
    if isinstance(t, Port):
        a, b = PORT_DIRECTION_TO_NODEREFS[t.direction]
        ports.append({"id": t.id, "coord": list(coord), "direction": t.direction.value, "nodes": [t.nodes[a], t.nodes[b]]})
ports.sort(key=lambda p: p["id"])
assert [p["id"] for p in ports] == list(range(len(ports)))
neighbors = [[v for v in STATIC_GRAPH.neighbors(n) if v < 54] for n in range(54)]
spiral = [ctx.tile_id[c] for c in spiral_land_coordinates(cmap.tiles, (2, -2, 0))]
tile_resources = [-1 if r is None else RES_IDX[r] for r in BASE_MAP_TEMPLATE.tile_resources]
port_resources = [-1 if r is None else RES_IDX[r] for r in BASE_MAP_TEMPLATE.port_resources]
assert len(tiles) == 19 and len(ports) == 9 and len(spiral) == 19 and len(tile_resources) == 19 and len(port_resources) == 9


# --- pixel geometry (pointy-top hexes, unit circumradius): tile centre from cube coords, vertices at
# N, NE, SE, S, SW, NW = -90, -30, 30, 90, 150, 210 degrees.
def center(coord):
    q, r, _ = coord
    return (math.sqrt(3) * (q + r / 2), 1.5 * r)


node_xy = [None] * 54
for t in tiles:
    cx, cy = center(t["coord"])
    for k, n in enumerate(t["nodes"]):
        ang = math.radians(-90 + 60 * k)
        node_xy[n] = [round(cx + math.cos(ang), 4), round(cy + math.sin(ang), 4)]
assert all(p is not None for p in node_xy)
for t in tiles:
    t["center"] = [round(v, 4) for v in center(t["coord"])]
for p in ports:
    p["center"] = [round(v, 4) for v in center(p["coord"])]

edges = ctx.edges  # edge idx -> (a, b), the engine's numbering

topology = {
    "tiles": tiles, "ports": ports, "edges": [list(e) for e in edges], "neighbors": neighbors, "node_xy": node_xy,
    "spiral_tile_ids": spiral, "numbers_spiral": list(BASE_NUMBERS_IN_SPIRAL_ORDER),
    "tile_resources": tile_resources, "port_resources": port_resources, "resources": list(RESOURCES),
}
(ROOT / "web/src/data").mkdir(parents=True, exist_ok=True)
(ROOT / "web/src/data/topology.json").write_text(json.dumps(topology, separators=(",", ":")))


def rs_arr(rows):
    return "[" + ", ".join("[" + ", ".join(str(v) for v in r) + "]" for r in rows) + "]"


rs = ["//! Generated by tools/dump_engine_consts.py from the pinned catanatron BASE map template. Do not edit.",
      "", f"pub const TILE_NODES: [[u8; 6]; 19] = {rs_arr([t['nodes'] for t in tiles])};",
      f"pub const PORT_NODES: [[u8; 2]; 9] = {rs_arr([p['nodes'] for p in ports])};",
      "pub const NEIGHBORS: [&[u8]; 54] = [" + ", ".join("&[" + ", ".join(str(v) for v in nb) + "]" for nb in neighbors) + "];",
      f"pub const SPIRAL_TILE_IDS: [u8; 19] = [{', '.join(str(v) for v in spiral)}];",
      f"pub const NUMBERS_SPIRAL: [u8; 18] = [{', '.join(str(v) for v in BASE_NUMBERS_IN_SPIRAL_ORDER)}];",
      f"pub const TILE_RESOURCES: [i8; 19] = [{', '.join(str(v) for v in tile_resources)}];",
      f"pub const PORT_RESOURCES: [i8; 9] = [{', '.join(str(v) for v in port_resources)}];", ""]
(ROOT / "catan_engine/src/base_topology.rs").write_text("\n".join(rs))

# --- layout: the spec rust_bridge builds, plus the static (tile/port) feature indices
spec = rb.layout_spec(ctx)
(ROOT / "catan_engine/src/base_layout.json").write_text(json.dumps(spec, separators=(",", ":")))
print("tiles", len(tiles), "ports", len(ports), "edges", len(edges), "features", spec["n_features"])
